name: publish-packages
on:
  push:
    branches:
      - test/publish-workflows

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Lerna Publish Packages
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.DIVOPS_PACKAGES_NPM_TOKEN }}
        run: |
          yarn install
          yarn lerna version --conventional-commits --yes --git-remote origin
          yarn lerna publish from-git --yes --concurrency=4
